image: ubuntu/22.04
packages:
  - python3
  - python3-pip
  - postgresql
tasks:
  - build: |
      cd mataroa
      pip3 install -r requirements.txt
  - test: |
      cd mataroa
      sudo -u postgres psql -U postgres -d postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
      export DEBUG=1
      export DATABASE_URL='postgres://postgres:postgres@localhost:5432/postgres'
      python3 manage.py collectstatic --noinput
      python3 manage.py test
  - lint: |
      sudo -u root apt install shellcheck
      cd mataroa
      touch .envrc
      pip3 install -r requirements.dev.txt
      pip3 install -r requirements.txt
      export PATH=/home/build/.local/bin:$PATH
      make lint
