# Generated by Django 3.0.6 on 2020-05-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blog_title",
            field=models.CharField(default="Default Title", max_length=500),
            preserve_default=False,
        ),
    ]
