# Generated by Django 3.0.6 on 2020-05-30 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_auto_20200530_0046"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("slug", "owner")},
        ),
    ]
