# Generated by Django 3.0.6 on 2020-05-31 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_auto_20200530_1206"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
