# Generated by Django 3.0.6 on 2020-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_auto_20200531_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blog_byline",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
