# Generated by Django 3.0.6 on 2020-06-01 23:26

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_user_blog_byline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="This will be your subdomain. Lowercase alphanumeric.",
                max_length=150,
                unique=True,
                validators=[main.validators.AlphanumericHyphenValidator()],
            ),
        ),
    ]
