# Generated by Django 3.0.6 on 2020-06-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_auto_20200601_2326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blog_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
