# Generated by Django 3.0.7 on 2020-06-07 00:23

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_auto_20200607_0017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_domain",
            field=models.CharField(
                help_text="DNS: CNAME your .mataroa.blog subdomain or A with IP 95.217.176.64",
                max_length=150,
                null=True,
                validators=[main.validators.validate_domain_name],
            ),
        ),
    ]
