# Generated by Django 3.0.7 on 2020-06-07 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_auto_20200607_0024"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Leave blank to keep as draft/unpublished",
                null=True,
            ),
        ),
    ]
