# Generated by Django 3.0.7 on 2020-06-07 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_auto_20200607_2049"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_at", "-created_at"]},
        ),
    ]
