# Generated by Django 3.0.7 on 2020-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_auto_20200608_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="slug",
            field=models.CharField(default="default-slug", max_length=300),
            preserve_default=False,
        ),
    ]
