# Generated by Django 3.0.7 on 2020-06-08 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_auto_20200608_2117"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-uploaded_at"]},
        ),
    ]
