# Generated by Django 3.0.7 on 2020-06-08 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_auto_20200608_2141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Leave blank to keep as draft/unpublished. Use a future date for auto-posting.",
                null=True,
            ),
        ),
    ]
