# Generated by Django 3.0.7 on 2020-06-10 18:54

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(
                help_text="Alphanumeric with dashes.",
                max_length=300,
                validators=[main.validators.AlphanumericHyphenValidator()],
            ),
        ),
    ]
