# Generated by Django 3.0.7 on 2020-06-10 19:04

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_auto_20200610_1854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(
                help_text="Lowercase letters, numbers, and - (hyphen) allowed.",
                max_length=300,
                validators=[main.validators.AlphanumericHyphenValidator()],
            ),
        ),
    ]
