# Generated by Django 3.0.7 on 2020-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_user_footer_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="footer_note",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
