# Generated by Django 3.0.7 on 2020-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_auto_20200613_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="webring_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="webring_next_url",
            field=models.URLField(
                blank=True,
                help_text="URL to get webring's next website.",
                null=True,
                verbose_name="Webring next URL",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="webring_prev_url",
            field=models.URLField(
                blank=True,
                help_text="URL to get webring's previous website.",
                null=True,
                verbose_name="Webring previous URL",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="webring_url",
            field=models.URLField(
                blank=True,
                help_text="Informational URL.",
                null=True,
                verbose_name="Webring info URL",
            ),
        ),
    ]
