# Generated by Django 3.0.8 on 2020-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_auto_20200812_2102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(
                blank=True, default="Anonymous", max_length=150, null=True
            ),
        ),
    ]
