# Generated by Django 3.0.8 on 2020-08-12 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_auto_20200812_2126"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
    ]
