# Generated by Django 3.1 on 2020-08-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_auto_20200812_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytic",
            name="referer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
