# Generated by Django 3.1 on 2020-08-20 19:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_auto_20200816_1543"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("unsubscribe_key", models.UUIDField(default=uuid.uuid4)),
                (
                    "blog_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["email"]},
        ),
        migrations.CreateModel(
            name="PostNotificationRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post_notification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.postnotification",
                    ),
                ),
            ],
            options={"ordering": ["-sent_at"]},
        ),
    ]
