# Generated by Django 3.1 on 2020-08-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_auto_20200821_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_on",
            field=models.BooleanField(
                default=False,
                help_text="Allow/disallow people subscribing for new posts notifications",
            ),
        ),
    ]
