# Generated by Django 3.1 on 2020-08-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_user_notifications_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="postnotificationrecord",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.post"
            ),
        ),
    ]
