# Generated by Django 3.1 on 2020-08-21 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_auto_20200821_1659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postnotificationrecord",
            name="sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
