# Generated by Django 3.1 on 2020-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_auto_20200830_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="If checked, page link will not appear on the blog footer.",
            ),
        ),
    ]
