# Generated by Django 3.1 on 2021-01-11 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0050_auto_20210101_1509"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostNotification",
            new_name="Notification",
        ),
        migrations.RenameModel(
            old_name="PostNotificationRecord",
            new_name="NotificationRecord",
        ),
        migrations.RenameField(
            model_name="notificationrecord",
            old_name="post_notification",
            new_name="notification",
        ),
        migrations.AlterUniqueTogether(
            name="notificationrecord",
            unique_together={("post", "notification")},
        ),
    ]
