# Generated by Django 3.1 on 2021-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0052_auto_20210124_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
