# Generated by Django 3.1 on 2021-03-12 16:43

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_notification_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                help_text="To setup: Add an A record in your domain's DNS with IP 95.217.177.163",
                max_length=150,
                null=True,
                validators=[main.validators.validate_domain_name],
            ),
        ),
    ]
