# Generated by Django 3.1.7 on 2021-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0054_auto_20210312_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_zialucia",
            field=models.BooleanField(
                default=False,
                help_text="Enable/disable Zia Lucia theme with larger serif font.",
                verbose_name="Theme Zia Lucia",
            ),
        ),
    ]
