# Generated by Django 3.1.7 on 2021-03-24 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0057_auto_20210317_2321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analytic",
            name="referer",
        ),
    ]
