# Generated by Django 3.2 on 2021-04-29 15:06

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0059_auto_20210409_1320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Optional, but also the only way to recover password if forgotten.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="This is your subdomain. Lowercase alphanumeric.",
                max_length=150,
                unique=True,
                validators=[main.validators.AlphanumericHyphenValidator()],
            ),
        ),
    ]
