# Generated by Django 3.2 on 2021-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_auto_20210503_0035"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mail_export_on",
            field=models.BooleanField(
                default=False,
                help_text="Enable/disable auto emailing of account exports every month.",
                verbose_name="Mail export",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comments_on",
            field=models.BooleanField(
                default=False,
                help_text="Enable/disable comments for your blog.",
                verbose_name="Comments",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notifications_on",
            field=models.BooleanField(
                default=False,
                help_text="Allow/disallow people subscribing for email newsletter for new posts.",
                verbose_name="Newsletter",
            ),
        ),
    ]
