# Generated by Django 3.2 on 2021-05-17 00:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0063_exportrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="export_unsubscribe_key",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
