# Generated by Django 3.2 on 2021-05-17 00:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0065_remove_uuid_null_export_unsubscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="export_unsubscribe_key",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
