# Generated by Django 3.2 on 2021-05-23 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_add_uuid_field_export_unsubscribe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Analytic",
            new_name="AnalyticPost",
        ),
    ]
