# Generated by Django 3.2 on 2021-05-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0068_analyticpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticpage",
            name="path",
            field=models.CharField(max_length=300),
        ),
    ]
