# Generated by Django 4.0.3 on 2022-04-12 22:41

import binascii
import os

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0073_user_api_key"),
    ]

    def gen_api_key(apps, schema_editor):
        User = apps.get_model("main", "User")
        for row in User.objects.all():
            row.api_key = binascii.b2a_hex(os.urandom(16)).decode("utf-8")
            row.save(update_fields=["api_key"])

    operations = [
        migrations.RunPython(gen_api_key, reverse_code=migrations.RunPython.noop),
    ]
