# Generated by Django 4.0.3 on 2022-04-12 22:41

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0074_populate_api_key_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                default=main.models._generate_key, max_length=32, unique=True
            ),
        ),
    ]
