# Generated by Django 4.0.4 on 2022-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0075_remove_api_key_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="footer_note",
            field=models.CharField(
                blank=True,
                default="Powered by [mataroa.blog](https://mataroa.blog/).",
                help_text="Supports markdown",
                max_length=500,
                null=True,
            ),
        ),
    ]
