# Generated by Django 4.0.4 on 2022-05-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0076_alter_user_footer_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
