# Generated by Django 4.0.4 on 2022-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0077_comment_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme_zialucia",
            field=models.BooleanField(
                default=False,
                help_text="Enable/disable Zia Lucia theme with larger font size.",
                verbose_name="Theme Zia Lucia",
            ),
        ),
    ]
