# Generated by Django 4.0.4 on 2022-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0078_alter_user_theme_zialucia"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_sansserif",
            field=models.BooleanField(
                default=False,
                help_text="Force sans-serif font in blog content.",
                verbose_name="Theme Sans-serif",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme_zialucia",
            field=models.BooleanField(
                default=False,
                help_text="Enable/disable Zia Lucia theme with larger default font size.",
                verbose_name="Theme Zia Lucia",
            ),
        ),
    ]
