# Generated by Django 4.0.4 on 2022-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0080_alter_user_theme_sansserif"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_author",
            field=models.BooleanField(
                default=False, help_text="True if logged in author has posted comment."
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
