# Generated by Django 4.1 on 2022-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0082_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_backups_on",
            field=models.BooleanField(
                default=False,
                help_text="Enable/disable automatic post backups.",
                verbose_name="Snapshots On",
            ),
        ),
    ]
