# Generated by Django 4.1.3 on 2022-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0085_alter_user_footer_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blog_byline",
            field=models.TextField(
                blank=True, help_text="Supports markdown", null=True
            ),
        ),
    ]
