# Generated by Django 4.1.7 on 2023-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0086_alter_user_blog_byline"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
