# Generated by Django 4.2.4 on 2023-08-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0087_user_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="If checked, page link will not appear on the blog header.",
            ),
        ),
    ]
