# Generated by Django 4.2.6 on 2023-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0088_alter_page_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
