# Generated by Django 4.2.7 on 2023-11-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0092_alter_onboard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboard",
            name="problems",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="onboard",
            name="quality",
            field=models.CharField(max_length=300),
        ),
    ]
