# Generated by Django 4.2.7 on 2023-11-09 21:11

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Onboard = apps.get_model("main", "Onboard")
    for row in Onboard.objects.all():
        row.code = uuid.uuid4()
        row.save(update_fields=["code"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0094_onboard_code"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
