# Generated by Django 5.0.1 on 2024-01-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0098_alter_user_notifications_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscribe_note",
            field=models.CharField(
                blank=True,
                default="Subscribe via [RSS](/rss/) / [via Email](/newsletter/).",
                help_text="Default: Subscribe via [RSS](/rss/) / [via Email](/newsletter/).",
                max_length=350,
                null=True,
            ),
        ),
    ]
