# Generated by Django 5.0.2 on 2024-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0099_alter_user_subscribe_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboard",
            name="seo",
            field=models.CharField(default="-", max_length=300),
            preserve_default=False,
        ),
    ]
