# Generated by Django 5.0.2 on 2024-07-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0100_onboard_seo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="broadcasted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
