# Generated by Django 5.0.2 on 2024-07-12 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0101_post_broadcasted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationrecord",
            name="is_canceled",
        ),
    ]
