# Generated by Django 5.0.2 on 2024-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0102_remove_notificationrecord_is_canceled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="broadcasted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
