# Generated by Django 5.2.4 on 2025-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0103_alter_post_broadcasted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboard",
            name="problems",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="onboard",
            name="quality",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="onboard",
            name="seo",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
