# Generated by Django 5.2.5 on 2025-08-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0104_alter_onboard_problems_alter_onboard_quality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_connect_account_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Connect account ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_connect_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID for subscriptions (platform account)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_connect_product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product ID (platform account)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscriptions_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable paid subscriptions for this blog",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_price_cents",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Price in cents (e.g., 500 = $5.00) for the monthly subscription",
            ),
        ),
        migrations.CreateModel(
            name="ReaderSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_account_id", models.CharField(max_length=100)),
                ("stripe_customer_id", models.CharField(max_length=100)),
                ("stripe_subscription_id", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]


