---
- hosts: virtualmachines
  vars_files:
    - vars.yaml
  become: yes
  tasks:
    - name: ping
      ansible.builtin.ping:

    # repository
    - name: clone
      ansible.builtin.git:
        repo: https://github.com/mataroa-blog/mataroa
        dest: /var/www/mataroa
        version: ansible
        accept_hostkey: true
      become_user: deploy
    - name: dependencies
      ansible.builtin.pip:
        virtualenv_command: python3 -m venv .venv
        virtualenv: /var/www/mataroa/.venv
        requirements: /var/www/mataroa/requirements.txt
      become_user: deploy

    # deployment specific
    - name: collectstatic
      ansible.builtin.shell:
        cmd: |
          source .venv/bin/activate
          python3 manage.py collectstatic --no-input
        chdir: /var/www/mataroa
      args:
        executable: /bin/bash
      become_user: deploy
    - name: migrations
      ansible.builtin.shell:
        cmd: |
          source .venv/bin/activate
          DATABASE_URL='{{ database_url }}' python3 manage.py migrate --no-input
        chdir: /var/www/mataroa
      args:
        executable: /bin/bash
      become_user: deploy
    - name: gunicorn restart
      ansible.builtin.systemd:
        name: mataroa
        state: restarted
    - name: caddy restart
      ansible.builtin.systemd:
        name: caddy
        state: restarted
